### ISSUE TITLE
How to solve this question?

### ISSUE THREAD

**Issue by KelleyYin** [xmfbit/DQN-FlappyBird#1]
I cann't understand this function's means.
line 88, in frame_step
    self.playerIndex = PLAYER_INDEX_GEN.next()
AttributeError: 'itertools.cycle' object has no attribute 'next'

**Comment by xmfbit** [comment]
@KelleyYin Hi, are you using Python2 or Python3? This has been removed in Python3. Maybe you can refer to this: https://stackoverflow.com/questions/5237611/itertools-cycle-next to fix it on your own.

**Comment by KelleyYin** [comment]
Very thanks ! I have solved this question.
